[env:ttgo-t-display]
platform = espressif32
board = ttgo-t1
framework = arduino
lib_deps =
    https://github.com/lathoub/Arduino-BLE-MIDI.git
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-59270096521
upload_port = /dev/cu.usbserial-59270096521